# Generated by Django 4.1.3 on 2022-12-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="designation",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
