# Generated by Django 4.1.3 on 2022-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('intake', 'intake'), ('used_like_new', 'used_like_new'), ('used', 'used'), ('damage_but_useable', 'damage_but_useable')], max_length=20)),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandOverOrReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(choices=[('intake', 'intake'), ('used_like_new', 'used_like_new'), ('used', 'used'), ('damage_but_useable', 'damage_but_useable')], max_length=20)),
                ('handover_or_return', models.CharField(choices=[('return_to_admin', 'return_to_admin'), ('handover_to_employee', 'handover_to_employee')], max_length=20)),
                ('handover_date', models.DateField()),
            ],
            options={
                'db_table': 'handovers',
                'ordering': ['-created_at'],
            },
        ),
    ]
