# Generated by Django 4.1.3 on 2022-12-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='belongs_to',
            field=models.CharField(choices=[('admin', 'admin'), ('employee', 'employee')], default='admin', max_length=20),
        ),
    ]
