# Generated by Django 4.1.3 on 2022-12-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_belongs_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoverorreturn',
            name='handover_or_return',
        ),
    ]
