# Generated by Django 4.1.3 on 2022-12-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_remove_handoverorreturn_handover_or_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverorreturn',
            name='transfer_to',
            field=models.CharField(choices=[('admin', 'admin'), ('employee', 'employee')], default='admin', max_length=20),
        ),
    ]
