# Generated by Django 4.1.3 on 2022-12-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0006_handoverorreturn_transfer_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="handoverorreturn",
            name="returning_period",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
