# Generated by Django 4.1.3 on 2022-12-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0007_handoverorreturn_returning_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handoverorreturn",
            name="returning_period",
        ),
        migrations.AddField(
            model_name="handoverorreturn",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
