# Generated by Django 4.1.3 on 2022-12-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0008_remove_handoverorreturn_returning_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="handoverorreturn",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
